-- 0006_invoice_counters.sql
-- Per-tenant official number counters (PROJECT_SPEC §11: "Official sequential
-- invoice numbers are generated by the database only, inside the RPC").
-- Counters are incremented with a row lock (UPDATE ... RETURNING) so two
-- concurrent transactions can never produce the same number.
-- Number formats: sales  S-000001, purchases P-000001, journal entry_no bigint.

begin;

create table public.invoice_counters (
    tenant_id   uuid primary key references public.tenants(id) on delete cascade,
    sale_no     bigint not null default 0 check (sale_no >= 0),
    purchase_no bigint not null default 0 check (purchase_no >= 0),
    journal_no  bigint not null default 0 check (journal_no >= 0)
);

alter table public.invoice_counters enable row level security;

create policy tenant_isolation on public.invoice_counters
    for all
    using (tenant_id = public.get_my_tenant_id())
    with check (tenant_id = public.get_my_tenant_id());

grant select, insert, update on public.invoice_counters to authenticated;
revoke all on public.invoice_counters from anon;

-- Ensures a counter row exists for the tenant, then returns the next official
-- invoice number for the given type ('sale'/'purchase').
create or replace function public.next_invoice_no(p_type text)
returns text
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_tenant uuid := public.get_my_tenant_id();
    v_next   bigint;
begin
    if p_type not in ('sale', 'purchase') then
        raise exception 'نوع غير صحيح للرقم التسلسلي';
    end if;

    if v_tenant is null then
        raise exception 'يجب تسجيل الدخول أولاً';
    end if;

    insert into public.invoice_counters (tenant_id)
    values (v_tenant)
    on conflict (tenant_id) do nothing;

    if p_type = 'sale' then
        update public.invoice_counters
           set sale_no = sale_no + 1
         where tenant_id = v_tenant
        returning sale_no into v_next;
    else
        update public.invoice_counters
           set purchase_no = purchase_no + 1
         where tenant_id = v_tenant
        returning purchase_no into v_next;
    end if;

    return case p_type
        when 'sale'     then 'S-' || lpad(v_next::text, 6, '0')
        when 'purchase' then 'P-' || lpad(v_next::text, 6, '0')
    end;
end;
$$;

-- Per-tenant journal entry number.
create or replace function public.next_journal_no()
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_tenant uuid := public.get_my_tenant_id();
    v_next   bigint;
begin
    if v_tenant is null then
        raise exception 'يجب تسجيل الدخول أولاً';
    end if;

    insert into public.invoice_counters (tenant_id)
    values (v_tenant)
    on conflict (tenant_id) do nothing;

    update public.invoice_counters
       set journal_no = journal_no + 1
     where tenant_id = v_tenant
    returning journal_no into v_next;

    return v_next;
end;
$$;

revoke all on function public.next_invoice_no(text) from public;
revoke all on function public.next_journal_no()     from public;

grant execute on function public.next_invoice_no(text) to authenticated;
grant execute on function public.next_journal_no()     to authenticated;

commit;